# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltmkoqHQBbdcK7_m9_lJCX0YAurmIra3

Project Title:
Multistep Methods: Adams–Bashforth and Adams–Moulton Methods

This project focuses on the implementation and analysis of important multistep numerical methods used for solving Ordinary Differential Equations (ODEs). In particular, the Adams–Bashforth methods (AB2, AB3), the Adams–Moulton method (AM2), and a predictor–corrector approach are implemented and studied.

* The main objectives of this project are:

* To implement different multistep numerical methods

* To compare their performance with the Runge–Kutta 4th order (RK4) method using identical step sizes

* To analyze stability issues and numerical errors

* To visualize results using appropriate stability plots and error curves

The project is implemented in Python using the Google Colab environment, which provides a convenient and reliable platform for numerical computation and visualization. All algorithms are implemented step by step, and detailed explanations are provided through in-code comments to clearly describe the working principles of each method.

To evaluate the performance of the numerical methods, a standard Ordinary Differential Equation (ODE) is considered:

dy/dt = -10y
y(0) = 1

This equation represents a stiff problem, which is suitable for analyzing the stability behavior of multistep methods. Since the exact solution is known, numerical errors can be easily computed and compared
"""

# Importing required numerical and plotting libraries
import numpy as np
import matplotlib.pyplot as plt

# Definition of the ODE
# y' = f(t, y)
def f(t, y):
    return -10 * y  # Stiff ODE to demonstrate stability issues

# Exact analytical solution
def exact_solution(t):
    return np.exp(-10 * t)

"""RK4:

* Single-step method

* High accuracy (4th order)

* Good Stability
"""

def rk4(f, y0, t):
    """
    Classical 4th order Runge-Kutta method.
    Used as a reference solution for comparison.
    """
    y = np.zeros(len(t))
    y[0] = y0
    h = t[1] - t[0]

    for n in range(len(t) - 1):
        k1 = f(t[n], y[n])
        k2 = f(t[n] + h/2, y[n] + h*k1/2)
        k3 = f(t[n] + h/2, y[n] + h*k2/2)
        k4 = f(t[n] + h, y[n] + h*k3)

        y[n+1] = y[n] + (h/6)*(k1 + 2*k2 + 2*k3 + k4)

    return y

"""Adams–Bashforth 2-Step (AB2)"""

def ab2(f, y0, t):
    """
    Adams-Bashforth 2-step explicit multistep method.
    """
    h = t[1] - t[0]
    y = np.zeros(len(t))
    y[0] = y0

    # Starting value obtained using RK4
    y[1] = rk4(f, y0, t[:2])[-1]

    for n in range(1, len(t) - 1):
        y[n+1] = y[n] + h * (
            3/2 * f(t[n], y[n]) -
            1/2 * f(t[n-1], y[n-1])
        )

    return y

"""Adams–Bashforth 3-Step (AB3)"""

def ab3(f, y0, t):
    """
    Adams-Bashforth 3-step explicit multistep method.
    """
    h = t[1] - t[0]
    y = np.zeros(len(t))
    y[0] = y0

    # Initial values using RK4
    y[1] = rk4(f, y0, t[:2])[-1]
    y[2] = rk4(f, y0, t[:3])[-1]

    for n in range(2, len(t) - 1):
        y[n+1] = y[n] + h * (
            23/12 * f(t[n], y[n]) -
            16/12 * f(t[n-1], y[n-1]) +
            5/12 * f(t[n-2], y[n-2])
        )

    return y

"""Adams–Moulton 2-Step (AM2 – Implicit)"""

def am2(f, y0, t):
    """
    Adams-Moulton 2-step implicit method.
    Predictor is used to handle implicit nature.
    """
    h = t[1] - t[0]
    y = np.zeros(len(t))
    y[0] = y0

    y[1] = rk4(f, y0, t[:2])[-1]

    for n in range(1, len(t) - 1):
        # Predictor (Euler method)
        y_pred = y[n] + h * f(t[n], y[n])

        # Corrector (AM2 formula)
        y[n+1] = y[n] + h/2 * (
            f(t[n+1], y_pred) + f(t[n], y[n])
        )

    return y

"""Predictor–Corrector Method"""

def predictor_corrector(f, y0, t):
    """
    Predictor-Corrector method:
    Predictor: Adams-Bashforth 2-step
    Corrector: Adams-Moulton 2-step
    """
    h = t[1] - t[0]
    y = np.zeros(len(t))
    y[0] = y0

    y[1] = rk4(f, y0, t[:2])[-1]

    for n in range(1, len(t) - 1):
        y_pred = y[n] + h * (
            3/2 * f(t[n], y[n]) -
            1/2 * f(t[n-1], y[n-1])
        )

        y[n+1] = y[n] + h/2 * (
            f(t[n+1], y_pred) + f(t[n], y[n])
        )

    return y

"""Numerical Experiment & Error Analysis"""

h = 0.1  # Step size (increase to show instability)
t = np.arange(0, 1 + h, h)
y0 = 1

y_exact = exact_solution(t)
y_rk4 = rk4(f, y0, t)
y_ab2 = ab2(f, y0, t)
y_ab3 = ab3(f, y0, t)
y_am2 = am2(f, y0, t)
y_pc = predictor_corrector(f, y0, t)

"""Error Curves Plot"""

plt.figure()
plt.plot(t, abs(y_ab2 - y_exact), label="AB2")
plt.plot(t, abs(y_ab3 - y_exact), label="AB3")
plt.plot(t, abs(y_am2 - y_exact), label="AM2")
plt.plot(t, abs(y_pc - y_exact), label="Predictor-Corrector")
plt.plot(t, abs(y_rk4 - y_exact), label="RK4")

plt.yscale("log")
plt.xlabel("t")
plt.ylabel("Absolute Error")
plt.title("Error Comparison of Numerical Methods")
plt.legend()
plt.grid(True)
plt.show()

"""Stability Discussion:

Due to limited stability regions, explicit Adams–Bashforth methods exhibit instability for larger step sizes. In contrast, Adams–Moulton and predictor–corrector methods show improved stability. The RK4 method provides the most stable reference solution for comparison.
"""
